name: Deploy

on:
  push:
    branches:
      - development
      - production
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: ${{ (github.ref == 'refs/heads/production') && 'production' || 'development' }}
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      COMMITTER: ${{ github.actor }}
      DOCKER_IMAGE: ghcr.io/hackthebox/hackster:${{ github.sha }}
      LATEST_IMAGE: ghcr.io/hackthebox/hackster:development
      CHANGE_CAUSE: ${{ github.run_number }}-${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: makelarisjr
          password: ${{ secrets.GH_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_IMAGE }},${{ env.LATEST_IMAGE }}
      - name: Rollout release
        uses: makelarisjr/kubectl-action@v1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: |
            set image deployment noahbot noahbot=${{ env.DOCKER_IMAGE }};
            kubectl annotate deployment noahbot kubernetes.io/change-cause="${{ env.CHANGE_CAUSE }}";
      - name: Send project deployed notification
        if: success() && github.ref == 'refs/heads/production'
        run: |
          ./.github/slack_notification.sh deployed
      - name: Send deployment failed notification
        if: failure() && github.ref == 'refs/heads/production'
        run: |
          ./.github/slack_notification.sh failed
